config/routes.rb
Artreads::Application.routes.draw do
  resources :roles

  devise_for :users,  :controllers => { :registrations => "registrations" }
resources :users
root :to => 'welcome#index'  # The priority is based upon order of creation:

end

app/models/user.rb
class User < ActiveRecord::Base
has_and_belongs_to_many :roles
# Determines whether or not a user has a role
#
# @param role Name of the role to search for
# @return [Boolean] True if the user has the specified role
def role?(role)
  return !!self.roles.find_by_name(role.to_s.camelize)
end
has_many :oauth_profiles
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise  :database_authenticatable, :token_authenticatable, :oauthable, :recoverable, :registerable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
attr_accessible :username
attr_accessible :default_provider
  attr_accessible :email, :password, :password_confirmation, :remember_me
  validate :username_or_email_exists  
  
  # Used for validation.  Validates whether a username or email exists because one is required.
  def username_or_email_exists
    if username.blank? && email.blank?
      self.errors.add(:email, "or Username is required.")
    end
  end
  
  # Returns the user's email or username depending on which is set
  # @return [String] Return username unless it is blank, then return email
  def display_name
    return self.username.blank? ? self.email : self.username
  end

  class << self
    # Join to the user role habtm table that restricts output to super admins
    def superadmins
      joins("join roles_users on users.id = roles_users.user_id").where("roles_users.role_id = (select id from roles where name = 'SuperAdmin')");
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :get_user, :only => [:index,:new,:edit]
  before_filter :accessible_roles, :only => [:new, :edit, :show, :update, :create]
  #load and authorize resource is cancan's way of filtering controllers.
  load_and_authorize_resource

  # GET /users
  # GET /users.xml                                                
  # GET /users.json                                       HTML and AJAX
  #-----------------------------------------------------------------------
  def index
    @super_admins = User.superadmins
    @super_admin_role = Role.find_by_name('SuperAdmin');
    @users = User.accessible_by(current_ability, :index).limit(20)
    respond_to do |format|
      format.json { render :json => @users }
      format.xml  { render :xml => @users }
      format.html
    end
  end

  # GET /users/new
  # GET /users/new.xml                                            
  # GET /users/new.json                                    HTML AND AJAX
  #-------------------------------------------------------------------
  def new
    respond_to do |format|
      format.json { render :json => @user }   
      format.xml  { render :xml => @user }
      format.html
    end
  end

  # GET /users/1
  # GET /users/1.xml                                                       
  # GET /users/1.json                                     HTML AND AJAX
  #-------------------------------------------------------------------
  def show
    respond_to do |format|
      format.json { render :json => @user }
      format.xml  { render :xml => @user }
      format.html      
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end

  # GET /users/1/edit                                                      
  # GET /users/1/edit.xml                                                      
  # GET /users/1/edit.json                                HTML AND AJAX
  #-------------------------------------------------------------------
  def edit
    respond_to do |format|
      format.json { render :json => @user }   
      format.xml  { render :xml => @user }
      format.html
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end

  # DELETE /users/1     
  # DELETE /users/1.xml
  # DELETE /users/1.json                                  HTML AND AJAX
  #-------------------------------------------------------------------
  def destroy
    @user.destroy

    respond_to do |format|
      format.json { render :json => "Ok" }
      format.xml  { head :ok }
      format.html { redirect_to( users_path, :notice => "The account has been deleted." ) }      
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end

  # POST /users
  # POST /users.xml         
  # POST /users.json                                      HTML AND AJAX
  #-----------------------------------------------------------------
  def create
    @user = User.new(params[:user])

    if @user.save
      respond_to do |format|
        format.json { render :json => @user.to_json, :status => 200 }
        format.xml  { head :ok }
        format.html { redirect_to :action => :index }
      end
    else
      respond_to do |format|
        format.json { render :text => "Could not create user", :status => :unprocessable_entity } # placeholder
        format.xml  { head :ok }
        format.html { render :action => :new, :status => :unprocessable_entity }
      end
    end
  end
  
  
  # Get roles accessible by the current user
  #----------------------------------------------------
  def accessible_roles
    @accessible_roles = Role.accessible_by(current_ability,:read)
  end

  # Make the current user object available to views
  #----------------------------------------
  def get_user
    @current_user = current_user
  end

  # PUT /users/1
  # PUT /users/1.xml
  # PUT /users/1.json                                            HTML AND AJAX
  #----------------------------------------------------------------------------
  def update
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank? 
      [:password,:password_confirmation,:current_password].collect{|p| params[:user].delete(p) }
    else
      @user.errors[:base] << "Your passwords don't match" unless params[:user][:password] == params[:user][:password_confirmation]
      #the following can be used if you have an update profile page.
      #@user.errors[:base] << "The password you entered is incorrect" unless @user.valid_password?(params[:user][:current_password])
    end

    respond_to do |format|
      if @user.errors[:base].empty? and @user.update_attributes(params[:user])
        @user.roles = []
        params[:user]['role_ids'].each do |role_id|
          if role_id != '' 
            @user.roles << Role.find_by_id(role_id)
          end
        end
        @user.save
        flash[:notice] = "The account has been updated"
        format.json { render :json => @user.to_json, :status => 200 }
        format.xml  { head :ok }
        format.html { render :action => :show }
      else
        format.json { render :text => "Could not update user", :status => :unprocessable_entity } #placeholder
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
        format.html { render :action => :edit, :status => :unprocessable_entity }
      end
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:js, :xml, :html)
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  
  <!-- extra fields go here -->
  
  <p><%= f.label :email %></p>
  <p><%= f.text_field :email %></p>

  <% if can? :read, Role %>
  	<p><%= f.label :role %></p>
  	<ul class="no-pad no-bullets">
  		<%= habtm_checkboxes(@user, :role_ids, @accessible_roles, :name) %>
  	</ul>
  <% end %>
  
  
  <p><%= f.label :password %> <i>(leave blank if you don't want to change it)</i></p>
  <p><%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %></p>
  <p><%= f.password_field :password_confirmation %></p>
  
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/users/edit.html.erb
<h3><%= @user == @current_user ? "Your Account Settings" : "Edit User" %></h3>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', user_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Roles</th>
    <th></th>
    <th></th>
  </tr>

  <!-- table header stuff here -->
  <% @users.each do |u| %>
    <tr>
      <td><%= "#{u.email}" %></td>
      <td><%= "#{u.roles.collect{|r| r.name}}" %></td>
      <td><%= link_to 'Show', user_path(u.id) %></td>
      <td><%= link_to_if(can?(:edit, User), 'Edit', edit_user_path(u.id)) {} %></td>
      <% if !(@super_admins.count == 1 && u.roles.include?(@super_admin_role)) %>
        <td><%= link_to_if(can?(:delete, u), 'Delete', u, :confirm => "Are you sure?", :method => :delete) {} %></td>
      <% else %>
        <td><span title="Can NOT delete the last SuperAdmin user">Delete</span></td>
      <% end %>
    </tr>
  <% end %>
</table>

<br />

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', user_index_path %>

app/views/users/show.html.erb
<h3><%= @user.email %></h3>
 
<%= link_to_if(can?(:update,@user), "Edit", edit_user_path(@user)) %> |
<%= link_to_if(can?(:delete, @user), "Delete", user_path(@user), :confirm => "Are you sure?", :method => :delete) {} %>
 
<table class="one-column-emphasis">
	<tbody>
		<tr>
			<td class="oce-first">Email:</td>
			<td><%= @user.email %></td>
		</tr>
		<tr>
			<td class="oce-first">Username:</td>
			<td><%= @user.username %></td>
		</tr>
		<tr>
			<td class="oce-first">Role:</td>
			<td><%= @user.roles.first.name %></td>
		</tr>
	<% if can?(:see_timestamps,User) %>
		<tr>
			<td class="oce-first">Created at:</td>
			<td><%= @user.created_at %></td>
		</tr>
		<tr>
			<td class="oce-first">Last Sign In:</td>
			<td><%= @user.last_sign_in_at %></td>
		</tr>
		<tr>
			<td class="oce-first">Sign In Count:</td>
			<td><%= @user.sign_in_count %></td>
		</tr>
	<% end %>
	<% if @user.respond_to?(:oauth_profiles) %>
  	<% @user.oauth_profiles.each do |profile| %>
  	  <tr>
  			<td class="oce-first"><%= profile.provider %> username:</td>
  			<td><%= profile.username %></td>
  		</tr>
  		<tr>
  			<td class="oce-first"><%= profile.provider %> email:</td>
  			<td><%= profile.email %></td>
  		</tr>
  		<tr>
  			<td class="oce-first"><%= profile.provider %> name:</td>
  			<td><%= profile.name %></td>
  		</tr>
  		<tr>
  			<td class="oce-first"><%= profile.provider %> image:</td>
  			<td><img src='<%= profile.img_url %>' /></td>
  		</tr>
  	<% end %>
  <% end %>
	</tbody>
</table>